# Python

In [20]:
import numpy as np
#arrayメソッド
x1=np.array(1)  #スカラー
x2=np.array([1,2,3])    #ベクトル
x3=np.array([[1,2],
             [4,5],
             [7,8]])  #行列
x3.shape
x3.shape[0] #行の数
x3.reshape(2,3)
x3.reshape(-1,1)    #n行1列にしたいときは-1を指定
x3.ravel()  #行列からベクトルに変換できる


array([1, 2, 4, 5, 7, 8])

In [32]:
x3=np.array([[1,2],
             [4,5],
             [7,8]])  #行列
x3[0]   #   1行目
#   :は範囲指定するもの
x3[1:]  #   2行目からすべて取り出す
x3[:2]  #   2行目まで取り出す
x3[:]

x3[0,1] #   x3[0][1]
x3[:,1] #   1列のものすべて
x3[:,0]

array([1, 4, 7])

In [52]:
x3=np.array([[1,2],
             [4,5],
             [7,8]])  #行列

x3>4
x3[x3>4]    #   x3>4の要素をすべて取り出してベクトル化

a=np.arange(10).reshape(-1,1)
np.random.seed(0)
b=np.random.rand(10)  #   0~1までの乱数を10個
b=np.where(b>0.5,1,0).reshape(-1,1) #   whereはC++の?:と同じ
print(b)
a[:][b==1]  #   b==1となるときのaの要素をすべて取り出す

[[1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]]


array([0, 1, 2, 3, 5, 7, 8])

In [55]:
a=np.array([[1,2],
             [4,5],
             [7,8]])  #行列
b=np.array([[1,2],
             [4,5],
             [7,8]])  #行列
np.vstack((a,b))    #   縦方向に結合(タプルで引数指定することに注意)
np.hstack((a,b))    #   横方向に結合

array([[1, 2, 1, 2],
       [4, 5, 4, 5],
       [7, 8, 7, 8]])

In [57]:
np.arange(1,10)    #   1以上10未満の整数のベクトルを生成

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
np.zeros([3,3])
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [64]:
a=np.array([[1,2],
             [4,5],
             [7,8]])  #3*2行列
np.zeros_like(a)    #   要素がすべて0の3*2行列
np.ones_like(a)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [66]:
np.eye(3)   #   単位行列

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
np.linspace(0,1,11) # 0~1の範囲を11等分したベクトル

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [71]:
np.random.randn(10)    #   平均0,分散1の乱数を生成

array([ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323,
        0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574])

In [74]:
np.random.randint(0,100,10) #   0~100-1までの整数乱数を10個生成

array([34,  0,  0, 36, 53,  5, 38, 17, 79,  4])

In [79]:
a=np.array([[1,2],
             [4,5],
             [7,8]])  #行列
b=np.array([[1,2],
             [4,5],
             [7,8]])  #行列
#   四則演算
a+b
a-b
a*b
a/b

array([[ 1,  4],
       [16, 25],
       [49, 64]])

In [80]:
a**2    #   累乗

array([[ 1,  4],
       [16, 25],
       [49, 64]])

In [90]:
a**0.5  #   平方根


array([ 6.92820323,  7.        ,  8.30662386, 13.        , 12.76714533,
       13.85640646,  9.74679434, 14.03566885,  9.69535971,  0.        ,
       10.63014581, 13.34166406,  6.        , 12.72792206,  6.92820323,
        9.64365076, 11.44552314,  9.89949494,  6.4807407 , 10.58300524])

In [84]:
np.exp(a)   #   e^x

array([[0.69314718, 1.09861229],
       [1.60943791, 1.79175947],
       [2.07944154, 2.19722458]])

In [105]:
np.random.seed(0)
a=np.random.randint(0,200,20)
np.sum(a)   #   合計
np.mean(a)  #   平均
np.var(a)   #   分散
np.std(a)   #   標準偏差

np.max(a)   #   最大値
np.argmax(a)    #   最大値のインデックス
np.min(a)   #   最小値
np.argmin(a)    #   最小値のインデックス

7

In [107]:
np.random.seed(0)
a=np.random.randint(0,200,20)

a.dtype #   要素のデータ型

dtype('int32')

In [108]:
#   データ指定して配列生成
np.random.randint(0,200,20,dtype='int32')

array([ 81, 165,  25,  77,  72,   9, 148, 115, 197,  79, 175, 192,  82,
        99, 177,  29, 147, 147, 142, 167])

In [110]:
a=np.random.randn(10)
np.round(a,2)   #   小数点以下を2個にまるめる

array([ 1.46,  1.54,  0.57,  0.15, -1.08,  1.4 ,  1.79, -0.57,  0.18,
       -0.46])